# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 972fe7af91cde496b6424c359eb198af45ba6eceddc2b5676ac303242d3d56fc16fcb2fd821dbacf753897ef57a4776a9219e9afff8da3d052a63292e3f92ae1

test:
  secret_key_base: a393c574573b6b951e13e23b584f5e0dc1e0303f472dd820ffe1b72e2875b628f569f61db097478b963c6e211a37de23345cf106c9b9bee82998302889881908

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
